services:
  - type: web
    name: mon-assistant-ia
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 180
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_PAGE_ID
        sync: false
      - key: SHOPIFY_STORE_URL
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
